### ISSUE TITLE
Doesn't work with DNS IP in the router.

### ISSUE THREAD

**Issue by trjammu** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#1]
Hi, Thank you for the nice guide. Works fine with the VPN client in iPhones.
Updating the GCP instances IP as DNS server in the wifi router doesn't seem to pick up and dont see it being routed via pi-hole.

**Comment by rajannpatel** [comment]
This is by design, every device needs to have the Wireguard software installed so that it can communicate with your server on Google Cloud. Your router won't be able to reach Pi-Hole in Google Cloud without a VPN connection on the router itself.
