### ISSUE TITLE
Autoupdating PiHole

### ISSUE THREAD

**Issue by Kwbmm** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#10]
I believe the information about autoupdating PiHole that were specified in the OpenVPN version of this guide are still valid. @rajannpatel isn't that so?
If so, I can make a PR to add them here.

**Comment by rajannpatel** [comment]
They are indeed valid! A PR is appreciated :+1:
