### ISSUE TITLE
With Pi-Hole and Wireguard running on Google Compute Engine, DNS requests to Google owned domains time out when using a Full Tunnel on macOS or Windows, works fine on Android

### ISSUE THREAD

**Issue by harssh** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#12]
**edit the Allowed IPs on your Client Profile on your device to read 0.0.0.0/0, ::/0**

Using this instruction I can only access pihole admin panel everything else just time out.
But works perfectly on android mobile.
<img width="945" alt="Screen Shot 2020-06-12 at 9 48 54 PM" src="https://user-images.githubusercontent.com/2812994/84558181-8fa35600-acf6-11ea-87c2-788cb126aa41.png">

**Comment by rajannpatel** [comment]
I want to confirm, you are not reusing the same client profile on Android and macOS, are you? To clarify, you are using a separate Wireguard client profile for the laptop, and for your mobile device?

**Comment by harssh** [comment]
Yes they are different client configs. 
One other thing I noticed is Pihole admin is only accessible via [fd*:*:*::1]/admin but not via the IPv4 ip address from my macbook. But works perfectly fine with my mobile.

Also just tested bi creating a new client config. Works same way for macbook.

**Comment by rajannpatel** [comment]
I'm able to replicate this issue on macOS Catalina 10.15.5 with Wireguard App version: 0.0.20191105 (16). I need some time to investigate, and I hope others can weigh in as well.

**Comment by rajannpatel** [comment]
I think we are closer to figuring this out. Only `google.com` is blocked, but any other domain `github.com` or `bing.com` work fine.

**Comment by harssh** [comment]
Yes this is correct

**Comment by harssh** [comment]
Sorry to be bringer of bad news but after some time even github.com does not load properly 

<img width="1428" alt="Screen Shot 2020-06-13 at 10 06 56 PM" src="https://user-images.githubusercontent.com/2812994/84583801-7ff14380-adc2-11ea-8de4-c953f9bf0181.png">

**Comment by rajannpatel** [comment]
commit 8958d3d7b037e45dccec460c49a8d5a06403c930 should resolve this issue. In your client configuration file change this:

```
DNS = fd42:42:42::1, fd42:42:42::1
```

to this:

```
DNS = 10.66.66.1, fd42:42:42::1
```

**Comment by rajannpatel** [comment]
The issue may have something to do with Pi-Hole trying to edit the resolv.conf file managed by the systemd-resolved service, and then having those changes overwritten by Google Compute Engine.

https://github.com/pi-hole/docker-pi-hole/issues/503

**Comment by harssh** [comment]
Thank you

**Comment by harssh** [comment]
Will re-executing setup.sh update the config or I should try to do this manually ?

**Comment by rajannpatel** [comment]
> Will re-executing setup.sh update the config or I should try to do this manually ?

You can get the latest setup.sh and it will do what you need it to do for all new client .conf files you generate:

```
sudo su -
curl -O https://raw.githubusercontent.com/rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs/master/setup.sh
chmod +x setup.sh
bash ./setup.sh 
```

But, your existing .conf files will have to be edited manually from within the Wireguard app in each of your clients. You can optionally keep the copy of the client .conf file on the server up to date, in case you re-import the client file from server using the QR Code.
