### ISSUE TITLE
Wireguard works, Pi-Hole works, but cannot access the admin panel for Pi-Hole (iOS)

### ISSUE THREAD

**Issue by roachman5000** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#19]
Hi!

So I started all over and went start to finish on the tutorial.  The Google Cloud account is up and running, Pi-hole is installed and working, and so is Wireguard (iOS).  It works but I cannot access the Pi Hole admin panel from either the external IP or from the 10.66.66.2 address.  I also tried 10.66.66.1 just to make sure.  Thanks in advance!

**Comment by rajannpatel** [comment]
When your Wireguard connection is active, are you able to go to either: http://[fd42:42:42::1]/admin or http://10.66.66.1/admin

**Comment by roachman5000** [comment]
Thank you for replying!

I’m not sure what changed between the first post and now, but the admin panel shows when I use either address.  Interesting....

And now all the stats stay at 0 or 0%, but it’s definitely blocking ads and whatnot.

**Comment by roachman5000** [comment]
(Update):  Tried running pihole -r, it ran through it with no red x's, still saying zeroes across the board except for the blocklist, which since I've been able to access the admin panel, has been there

**Comment by rajannpatel** [comment]
Feel free to reopen this issue if you are still having problems. It's getting stale, so I'll close it for now.
