### ISSUE TITLE
Setup script not automatically incrementing IP Address for each new client profile

### ISSUE THREAD

**Issue by smadgal** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#2]
Line 15 in setup.sh needs to include full path to wg0-client* i.e. /root/wg0-client*. Otherwise, script runs great! Thank you for this awesome and easy setup!!

**Comment by rajannpatel** [comment]
you need to run `sudo su -` to become the root user, before running the script. i could write some defensive bash to identify when the script is not run as root. perhaps writing all the conf files into the /etc/wireguard location directory could be suitable, to avoid any confusion around running `setup.sh` as a non-root user.

**Comment by smadgal** [comment]
Thank you Rajan - did not realize that I needed to run the script as root. Perhaps all you need to do is mention that in your Readme. BTW, I just love how simple this is to setup and the added bonus of hosting on GCP for free!
