### ISSUE TITLE
comment in client's config file and custom path to store config files , maybe ?

### ISSUE THREAD

**Issue by changchichung** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#20]
now the script will generate the first client's config file like wg0-client-2.conf in root's home.
in my sceranio , I would like to rename the file to match user's name and devices 
like wg0-client-eric-iphone8.conf
but if I do the rename , then next time when I generate another client , the script will not be able to determine client's ip address and  then create wg0-client-2.conf again.
so if I want to use the script to keep generating config without modify client's ip address , then I will not be able to rename the config file.
then , how about add a "comment" in script's interactive process , and just add the comment into config file , so at least I can use grep to find out user's config ?

and also I think that is not proper to store config files in root's home directory , maybe it should be a customize variable ?

**Comment by rajannpatel** [comment]
You can rename `wg0-client-2-conf` to `wg0-client*`, where `*` can be whatever you want. Subsequent client generations will have their config filenames incrementally increased. Line 15 of setup.sh is responsible for this:

```bash
WG_CLIENT_COUNT=`expr $(ls -1q wg0-client* 2>/dev/null | wc -l) + 2`
```

I can look into the comment capabilities. Storing config elsewhere could be possible, but it becomes a breaking change for users, if they upgrade. It also opens up the possibility that people may scatter the config files around their system. A suitable option would be to drop them into a new directory under `/etc/wireguard/clients`?

**Comment by changchichung** [comment]
```/etc/wireguard/clients``` whould be great !

**Comment by rajannpatel** [comment]
client configs are stored in the user's home directory now, when deploying the latest versions of the software using this guide.
