### ISSUE TITLE
Network limitations on f1-micro VM free tier

### ISSUE THREAD

**Issue by JPUnD** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#21]
After looking through the [google cloud free tier](https://cloud.google.com/free/docs/gcp-free-tier), under the `Always Free` section, on the `Compute Engine` entry in the table, you can read the following:
```
- 1 non-preemptible f1-micro VM instance per month in one of the following US regions:
    - Oregon: us-west1
    - Iowa: us-central1
    - South Carolina: us-east1
- 30 GB-months HDD
- 5 GB-month snapshot storage in the following regions:
    - Oregon: us-west1
    - Iowa: us-central1
    - South Carolina: us-east1
    - Taiwan: asia-east1
    - Belgium: europe-west1
- 1 GB network egress from North America to all region destinations (excluding China and Australia) per month
```

If I understand correctly for each region you only have 1 GB of outbound traffic for free, is that correct?

**Comment by rajannpatel** [comment]
Clarity has been provided in multiple areas of the documentation, thanks for this feedback!

**Comment by mobilelifeful** [comment]
Hello @rajannpatel, Can you please confirm follow alone this guide, we already operate a Split Tunnel VPN for only our DNS traffic?
If not, can you please show us how to do that?   Thank you in advance.
