### ISSUE TITLE
Deleting client leaves unwanted residues

### ISSUE THREAD

**Issue by ghost** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#22]
When I use the command you provided `sudo wg set wg0 peer publicid remove` it does something to the VM instance, I can't connect the removed client. But when I terminate the connection to ssh and reconnect to it, and run the command `sudo wg show` I'm still able to see the so called "removed client", however I can't to the server from the client as it should because I ran the remove command. And when I delete it the peer info directly from the `/etc/wireguard/wg0.conf` after the command, it completely destroy the script when I want to add new client to my server. When I run the `bash ./setup.sh` after running the remove command and manually deleting the client info from the `/etc/wireguard/wg0.conf` it still can generate new clients but the newly generated clients won't work and the existing clients will run as if nothing happened. So what removing the peer info directly from the `/etc/wireguard/wg0.conf` after running the command does to the script and  what I should do to completely destroy the every remnant of deleted client? I'm new to this things by the way.

**Comment by jcat59** [comment]
Any update on this? Are you still around @rajannpatel ?

**Comment by rajannpatel** [comment]
I have a fix in my head, but I need time to get it into a shell script and tested. It's taking longer than I initially expected.

**Comment by jcat59** [comment]
Ok thanks Rajann!! Good to hear from you

**Comment by rajannpatel** [comment]
The `wireguard` command will provide an interface to add/list/remove VPN users when following the newest version of this guide.
