### ISSUE TITLE
setup.sh outputs `/etc/wireguard/params: No such file or directory` on Debian

### ISSUE THREAD

**Issue by danieltornroos** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#23]
I've tried to setup wireguard on my google cloud machine, but I get this issue:
./setup.sh: line 5: /etc/wireguard/params: No such file or directory

**Comment by rajannpatel** [comment]
I just spun up a new instance of Ubuntu 20.04 LTS Minimal on Google Cloud's Google Compute Engine service, and ran through the Quickstart steps. It does not error out as you have described. I would recommend deleting your virtual machine and trying it again? Let me know how it goes.

**Comment by danieltornroos** [comment]
Thanks, think the keyword is Ubuntu, I got debian on my VM. I'll delete and try again with ubuntu.

**Comment by rajannpatel** [comment]
Thanks for reporting the trouble with Debian, I'll look into that and see what can be done to resolve it. Can you clarify the version?

**Comment by danieltornroos** [comment]
I can confirm I got it working on Ubuntu, I do not know what version of Debian it was, just the default debian from the Google Cloud drop down.
