### ISSUE TITLE
Update to Option A Step 1

### ISSUE THREAD

**Issue by jprobst24** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#24]
Change suggestion 1:
Current:
"Name your Virtual Machine pi-hole.
To qualify for the Free Tier, your Region selection should be any US region only (excluding Northern Virginia [us-east4]). I have used us-east1 and the us-east1-b zone because it is closest to me.
Choose the f1-micro Machine Type in the dropdown."

Suggested Change:
"Name your Virtual Machine pi-hole.
To qualify for the Free Tier, your Region selection should be any US region only (excluding Northern Virginia [us-east4]). I have used us-east1 and the us-east1-b zone because it is closest to me.
**Change the Series to "N1"**
Choose the f1-micro Machine Type in the dropdown."

------

Change Suggestion 2:
Current:
"The External IP Address should not be Ephemeral. Choose Create IP Address to Reserve a New Static IP Address"

Suggested Change:
"In the External IP Address section,  change from "Ephemeral " to "Create IP Address" to reserve a new Static IP Address.
Click "Reserve".

**Comment by rajannpatel** [comment]
Thanks for the feedback, I have made the changes you have requested. Feel free to reopen this if there is anything I have missed.
