### ISSUE TITLE
Static IP on Google Compute Engine no longer free

### ISSUE THREAD

**Issue by dushyantahuja** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#25]
Looks like Google has started charging for the static IP and it is no longer free. Would Dynamic DNS like DuckDNS be a better option now?

**Comment by rajannpatel** [comment]
My understanding is the IP is still, and will always be free.

> Google Cloud Free Tier is also available for external IP addresses that are being used by VM instances. In-use external IP addresses are available without additional cost until you have used a number of hours equal to the total hours in the current month. Usage calculations are combined across all in-use external IP addresses across all regions. Google Cloud Free Tier for in-use external IP addresses applies to all non-preemptible instance types, not just f1-micro instances.

source: https://cloud.google.com/free/docs/gcp-free-tier

**Comment by dushyantahuja** [comment]
Thanks - looks like I had setup two IP addresses, and that's why was getting charged. User error :(

**Comment by dushyantahuja** [comment]
Not sure what's happening, my billing still shows a charge for static IP address. 
<img width="1147" alt="Screenshot 2020-10-12 at 08 12 29" src="https://user-images.githubusercontent.com/6416649/95699672-c1a3d500-0c62-11eb-8a86-ffe0adfaf43c.png">

**Comment by rajannpatel** [comment]
Click the Hamburger Menu on the top right, and under the Networking header click **VPC Network** >  **External IP Addresses**. You likely have more than 1 IP address here. Delete the unused one by clicking the checkbox next to it, and then clicking **Release Static Address** button at the top.

**Comment by rajannpatel** [comment]
There may have been a time when you had 2 IPs, so that charge is appearing from when you had multiple IPs. Also, it is worth noting, that if the Virtual Machine is powered off but the IP is still provisioned (and not released), then there is a charge for holding the IP.
