### ISSUE TITLE
Discrepancy between screenshot and instruction in Option A, Step 1, ii, 2

### ISSUE THREAD

**Issue by amanmore** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#26]
The written instruction currently says 

> Machine type: n1-standard-1 (1 vCPU, 3.75 GB memory)

While the screenshot shows 

> Machine Type: f1-micro

Which option should we go for?

**Comment by rajannpatel** [comment]
sorry about that typo, you need to be using the **f1-micro**
