### ISSUE TITLE
Updating Pi-Hole

### ISSUE THREAD

**Issue by sukuoru** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#27]
I just noticed a notification that there was an update to my Pi-Hole install, and was wondering how we would go about updating after using your script, if it is even recommended.

I also want to say thank you for going through the work of setting this all up, I used the old way you had of doing this and switched to this as soon as you put it up. Great work!

**Comment by sukuoru** [comment]
[Following this](https://docs.pi-hole.net/core/pihole-command/#update), I figured it out myself. For anyone else, simply SSH into your Cloud instance, and run the command `pihole -up`

It will check and install all pihole related updates, including your gravity list.

**Comment by jcat59** [comment]
> [Following this](https://docs.pi-hole.net/core/pihole-command/#update), I figured it out myself. For anyone else, simply SSH into your Cloud instance, and run the command `pihole -up`
> 
> It will check and install all pihole related updates, including your gravity list.

After I SSH into my google cloud instance, I tried 'pihole -up' or 'pihole -v' and it says "command not found". Do I need to be in a directory before running?
