### ISSUE TITLE
Price Estimate

### ISSUE THREAD

**Issue by raycekar** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#29]
I understand it is an estimate but does anyone know is this estimating based on if I go over limits and what not?  Or is this a new thing where you do have to rent a virtual server?
![image](https://user-images.githubusercontent.com/17347780/95256572-9c3d4400-07e8-11eb-858a-28aba517a6d7.png)

**Comment by ralphscheuerer** [comment]
As I understand, this is the estimated cost if you go over the first 744 hours per month. (Not counting egress traffic over 1GB which will be billed separately)

**Comment by raycekar** [comment]
How I read that, is it will give you 744 hours for free this month, but not for the next.  I've spent a little bit of time trying to find in the "Learn More" to see how it handles other months.

**Comment by rajannpatel** [comment]
It is 744 hours free every month. The estimate is there to help you understand what the costs would look like if you had more than 1 server running
