### ISSUE TITLE
Permission denied error while generating QR code for client config

### ISSUE THREAD

**Issue by smadgal** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#3]
Permission denied error trying to execute `qrencode -t ansiutf8 -l L < cat /root/wg0-client-2.conf`

Was able to generate QR code with sudo cat /root/wg0-client-2.conf | qrencode -t ansiutf8 -l L

**Comment by rajannpatel** [comment]
as mentioned in the other ticket, i had anticipated users to be `sudo su -` and in the **/root** directory when running `setup.sh`. I will have to think about how to solve for this in a backwards compatible way.

**Comment by smadgal** [comment]
Closing this since it is a non-issue - just need to run as root user.

**Comment by rajannpatel** [comment]
The sudo command you crafted works fine for both root and non-root users. I have revised the script to reflect this command to generate a QR code. Thanks for your contribution!
