### ISSUE TITLE
Update the excellent guide

### ISSUE THREAD

**Issue by kmajeed** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#36]
Hi. Firstly  thank you for writing up this excellent guide. I have setup my pi-hole server on GCP and its running. 
I have few questions which I think you can answer/add to your guide to make it more noob friendly..

1. How can I connect to web-interface of pi-hole to see stats and update block list? Is it only possible from connected clients other machines which are not connected to this VPN?
2. How do I add this VPN to Ubuntu/Kubuntu client machine for ad blocking? 
3. Is it possible to connect my TV to this VPN? I would like to detect which servers it connects to for calling home feature and if possible block youtube ads

**Comment by rajannpatel** [comment]
1. connect to the vpn and visit `http://10.66.66.1`
2. i think if you hold out long enough, a way to manage your wireguard tunnels will appear in the graphical user interface, if it's not there already. I don't have Ubuntu with a graphical user interface, so I'm a bit out of my wheelhouse. Hopefully other users can chime in here.
3. unless your router in your home is capable to connecting to the Google Cloud Compute instance using a VPN, you can't use the 10.66.66.1 address to reach the DNS server in your Google Cloud. You need a raspberry pi, an old computer, or a virtual machine in your computer, to run pihole in your house, to protect your TV
