### ISSUE TITLE
Misinformation about GCP's free tier in this guide?

### ISSUE THREAD

**Issue by Fanboy-Studios** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#37]
_Be aware of the limitations of the Free Usage Tier:_

_1 vCPU + 3.75GB RAM f1-micro virtual machine instance per month in one of the following US regions_

https://github.com/rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs/blob/master/GOOGLE-CLOUD.md

**Unless the RAM limit has changed, I think we are still limited to 640 MB of RAM. Correct me if I'm wrong... but when I made my server I only got 640 MB RAM as part of the free tier.**

**Comment by rajannpatel** [comment]
i went a little crosseyed and mixed up the numbers between the free tier and standard tier. you have a sharp eye for catching this!
