### ISSUE TITLE
Cannot access ipv6 addresses from ipv4 only network through the tunnel

### ISSUE THREAD

**Issue by kuduku1** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#38]
I have completed the guide successfully . My home network is ipv4 only . When i connect through the Wireguard tunnel i am not able to ping or open ipv6 only addresses .
Can this be done using the Wireguard tunnel ?

**Comment by rajannpatel** [comment]
The guide does not take into account an IPv6 public address, which may be available in the free tier. I am unsure...

You can reserve a public facing IPv6 address for your virtual machine, and be able to connect to IPv6 only endpoints once that is done.

https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address#reserve_new_static
