### ISSUE TITLE
Question on split tunnel and port forwarding

### ISSUE THREAD

**Issue by jcat59** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#39]
Hello and thanks for this excellent guide, which I recently used to set up a split tunnel in the cloud.

One question I have is that you say to forward port 51515 on the router. I don’t understand how this works, because I’m only able to forward ports to a device that is connected to my router (which is a google nest by the way). How can I forward it to a cloud device, and what purpose does it serve? I have my iPhone set as a client and pihole is working. However, there’s no protection in in masking my IP address.

Can you confirm what protection I have with just a split tunnel DNS? What safety does that provide outside my LAN, what does it encrypt? Just visiting websites?

appreciate any insite you can offer as I’m new to this and trying to learn. I’m also trying to decide if I should set this up on my local lab for a full tunnel, perhaps that’s more beneficial especially if I want to do file sharing as well.

**Comment by rajannpatel** [comment]
I think you may be mixing 2 things up. You can host the pihole inside your home, so it would be on a computer behind your Google Nest router, and your Google Nest router would assign that computer an IP address. The other option is to host pihole in the cloud, then you don't need to do anything with your Google Nest router.
