### ISSUE TITLE
Automating Wanguard installation with Docker, Terraform and Cloud Run

### ISSUE THREAD

**Issue by theclue** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#42]
Similarly on what it was done for AWS, I was wondering if there's a way to do the same for GCP: automating the deployment of Wanguard on serverless environment using Terraform, Cloud Run, Cloud Build and Docker

Theorically it should be possible I guess, but I saw that the included setup.sh file is not meant to be run headless so I was just wondering on what could this be overcome (if possible)

Actually, if CPU throttling of CloudRun is not a good deal, GCE would be still ok. But the headless setup issue remains I guess.

any suggestion appreciated!

**Comment by rajannpatel** [comment]
everything you can do with the google cloud web interface can be done through the command line with the gcloud command line tool (https://cloud.google.com/sdk/gcloud) - so there is a way to automate this at whatever scale you would like! it's not something i can whip together very quickly, but I would love to see a fork of this project go in that direction

**Comment by cosmopockets** [comment]
@theclue I'm interested in contributing to this fork or starting a fork to get some traction on this.

**Comment by rajannpatel** [comment]
I'm going all in on a writeup that uses the gcloud command line utility to deploy this, and the virtual machine will be configured through a cloud-init.yaml configuration. The new implementation will be faster to deploy, more secure, and more convenient to maintain.

**Comment by rajannpatel** [comment]
The cloud-init.yaml based guide is now complete :-)
