### ISSUE TITLE
pi.hole domain routed to incorrect IP

### ISSUE THREAD

**Issue by GMNGeoffrey** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#47]
Thanks for the great guide. I followed it a while ago to set up my pi-hole, which has been working great since. When recently switching to an e2-micro instance (see https://github.com/rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs/issues/45) I noticed that it is not possible to access the pi-hole admin page via http://pi.hole/admin. Notably, the [docs for this guide](https://github.com/rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs/blob/master/CONFIGURATION.md) only say it will be accessible at the IP address, but especially coming back to pi-hole after a while of not touching it, it was surprising that it didn't work as it does in the pihole documentation. I think the issue is that the IP address in /etc/pihole/local.list is the internal IP of the vm instance, not of wireguard, which is what is needed. I was able to work around this by adding a [local DNS record](http://pi.hole/admin/dns_records.php) in the pihole admin console pointing pi.hole to `10.66.66.1`. I wonder if there's a better solution or if this workaround should be documented in the guide.

**Comment by rajannpatel** [comment]
This local DNS record seems to be the most appropriate way of doing this, and the documentation should reflect this. I can make the update, but if you submit a pull request I would happily approve it

**Comment by GMNGeoffrey** [comment]
Sorry I forgot about this. #57 adds the documentation
