### ISSUE TITLE
Question - ubuntu autoupdate and clean

### ISSUE THREAD

**Issue by jcat59** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#49]
How do you ensure that Ubuntu stays up to date on the cloud server?

I like to run the below command manually. Would it be worth putting this on a schedule, similar to how you update pihole?

---
sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt clean -y && sudo apt autoclean -y

**Comment by jcat59** [comment]
thanks umatz

**Comment by rajannpatel** [comment]
https://landscape.canonical.com/ is well suited for this, and is what I use. Google Cloud also offers OS Patching: https://cloud.google.com/compute/docs/os-patch-management

**Comment by jcat59** [comment]
> https://landscape.canonical.com/ is well suited for this, and is what I use. Google Cloud also offers OS Patching: https://cloud.google.com/compute/docs/os-patch-management

Thanks - I'll check these out!
