### ISSUE TITLE
Change country 

### ISSUE THREAD

**Issue by addreeh** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#59]
Is there anyway to get an IP from another country without paying? I'm from Spain and a lot of websites are blocks, for example football webs. I would like to change my location to France and get access to those webs.
The only that I have found is to hire a VPN server but I would like to know if it is possible to setup a VPN server in another country from Spain for free.

**Comment by anbuchelva** [comment]
Hi @addreeh, I don't know the issue is still relevant.

You can try creating a server that is located in France to achieve it. Try Oracle Cloud by selecting region as France, if you want it free of cost.

**Comment by rajannpatel** [comment]
Only `us-west1`, `us-central1`, and `us-east` regions qualify for Google Cloud's free tier. Oracle's public cloud offering may be better suited for you.
