### ISSUE TITLE
I am unable to access my admin panel.

### ISSUE THREAD

**Issue by Fanboy-Studios** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#6]
I am unable to access my admin panel.

I've tried connecting to the VPN and going to http://10.66.66.1/admin as well as the external IP from GCP. Something is not working. I even enabled HTTP and HTTPS in the firewall.

**Comment by Fanboy-Studios** [comment]
I guess the setup script didn't quite make it through the whole setup the first time. I got it working now.

**Comment by rajannpatel** [comment]
I hope you have disabled HTTP and HTTPS in the firewall, it's not necessary for things to work. Glad it's sorted out!
