### ISSUE TITLE
IPv4 CIDR Block

### ISSUE THREAD

**Issue by Drtatom** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#63]
Hi
This project is no working in my Oracle instance (with Ubuntu 20.04). I was wondering if it is related with the IPv4 CIDR Block. I have assigned 10.0.0.0/24 but the setup use the range 10.66.66.*. 
Should I modify the setup file? In that case, How do I start again the full installation? Because when I enter setup again it only adds a new client rather install the whole project from scratch.
Thank you!

**Comment by rajannpatel** [comment]
You can manually provide the cloud-init.yaml file included in this repo when provisioning an Oracle Cloud VM, and the installation will be completed in an unattended manner.
