### ISSUE TITLE
Migration from old version of this guide to new version?

### ISSUE THREAD

**Issue by umatz** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#64]
Thank you so much for your effort and development of an even better version of this guide. 
As someone who is using a pi.hole solution based on the old version of this guide, is there a migration path to get the benefits of the new way?
Or should I just delete the old instance and create an new one from scratch following the new version of the guide?

**Comment by rajannpatel** [comment]
There isn't a clean migration path, unfortunately :-(

**Comment by umatz** [comment]
I just deleted the old instance and created a new one following the new guide. Thanks again for your work!
