### ISSUE TITLE
VPN connecting, but can't access Pi-Hole admin panel and not blocking ads

### ISSUE THREAD

**Issue by EDV11** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#8]
Hello,

I come from your other GitHub (PiVPN and PiHole) that worked flawlessly for quite a while, but had to remove the VM.

I configured the Wireguard through GCloud today. I've done it 2 or 3 times following every step, but I always end up the same.

I created two config files, one for Mac and another for iOS. I've installed both, and both VPNs are connecting fine and traffic flows fine. 

But ads are note being blocked, nor I can access Pi Hole admin panel either by http://[fd42:42:42::1]/admin, http://10.66.66.1/admin or http://pi.hole/admin. It doesn't respond to ping either.

I'm using the split configuration. If I try the full tunnel with 0.0.0.0/0, ::/0 then it won't connect.

Where should I look at?

Thanks

**Comment by EDV11** [comment]
By the way, I can access the Pi Hole admin panel if I go into the VM external IP address

**Comment by rajannpatel** [comment]
It seems like your Google Cloud Firewall ports need to be inspected. I want you to confirm Port 53 is closed. Go ahead and close Port 80 (default-http-allow) and Port 443 (default-allow-https), and open up Port 51515.

**Comment by rajannpatel** [comment]
Step 7 is the step I believe you may have missed:

Click the Hamburger Menu at the top left, click **VPC Network** and click **Firewall Rules**. <br><img src="https://github.com/rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs/raw/master/images/screenshots/firewall.png" width="222"> <br>Click **Create Firewall Rule** at the top center of the page. The name of your rule should be `allow-wireguard`, change the **Targets** dropdown to **All instances in the network**. The **Source IP Ranges** should be `0.0.0.0/0`. The **udp** checkbox should be selected, and the port number next to it should be changed from `all` to `51515`. Then click the **Create** button.

**Comment by EDV11** [comment]
Yes, you are right! As I was coming from PiVPN I assumed that I already had the Firewall setup... my bad!

Thanks!

**Comment by rajannpatel** [comment]
I added some language in the guide to help people coming from the old setup. Remember to delete the OpenVPN firewall rule, you don't need Port 1194 open anymore either. Feel free to ping back if you run into further trouble.

**Comment by roachman5000** [comment]
Hi!  I'm having the exact same issue, except the Pi Hole is working, but I cannot access the Pi Hole admin panel from either the VM internal or external IP to adjust the whitelist/blacklist.
